spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/

application:
  security:
    jwt:
      secret-key: 57E191DB25FC6664AB2865EEBBB38B868EC3AFDEAC8A767325AB3B1CDB
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

  server:
    port: 8080
